name: kokoland

services:
- name: web
  source_dir: /
  github:
    repo: yara279-gif/kokoland
    branch: main
  
  build_command: |
    pip install -r requirements.txt
    python manage.py collectstatic --noinput
    python manage.py migrate --noinput
  
  run_command: gunicorn kokoland.wsgi:application --bind 0.0.0.0:8080
  
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /

# Add a managed PostgreSQL database
# databases:
# - engine: PG
#   name: kokoland-db
#   version: "15"
#   size: db-s-1vcpu-1gb
#   num_nodes: 1