# Generated by Django 5.2.3 on 2025-11-30 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_published_date"),
        ("buying", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="customization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.customizations",
            ),
        ),
    ]
