# Generated by Django 5.2.3 on 2025-12-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_published_date"),
        ("buying", "0002_alter_purchaserequest_customization"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.book",
            ),
        ),
    ]
