# Generated by Django 5.2.3 on 2025-12-01 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_published_date"),
        ("buying", "0003_purchaserequest_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlibrary",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.book",
            ),
        ),
        migrations.AlterField(
            model_name="userlibrary",
            name="custom_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.customizations",
            ),
        ),
    ]
