# Generated by Django 5.2.3 on 2025-11-21 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("char_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("category", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=50)),
                ("cover_image", models.ImageField(upload_to="media/covers/")),
                ("gender", models.CharField(max_length=50)),
                ("rate", models.FloatField()),
                ("description", models.TextField()),
                ("published_date", models.DateField(default=django.utils.timezone.now)),
                ("book_file", models.FileField(upload_to="media/books/")),
            ],
        ),
        migrations.CreateModel(
            name="Customizations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(max_length=100)),
                ("child_image", models.ImageField(upload_to="media/child_images/")),
                ("child_age", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("custom_book", models.FileField(upload_to="media/custom_books/")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
