# Generated by Django 5.2.3 on 2025-11-27 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_alter_book_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
