# Generated by Django 5.2.3 on 2025-12-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_file_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customizations",
            name="child_image_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customizations",
            name="custom_book_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_file",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customizations",
            name="child_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customizations",
            name="custom_book",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
