# Generated by Django 5.2.3 on 2025-12-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_book_book_file_type_book_cover_image_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customizations",
            old_name="user_id",
            new_name="user",
        ),
    ]
